function(driverstationrtc_generate_exports target exports_file)
    file(STRINGS "${exports_file}" export_lines)
    set(symbols)

    foreach(line IN LISTS export_lines)
        string(STRIP "${line}" line)
        if(line STREQUAL "" OR line MATCHES "^#")
            continue()
        endif()
        list(APPEND symbols "${line}")
    endforeach()

    list(REMOVE_DUPLICATES symbols)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${exports_file}")

    set(generated_dir "${CMAKE_CURRENT_BINARY_DIR}/generated_exports")
    file(MAKE_DIRECTORY "${generated_dir}")

    if(WIN32)
        set(generated_file "${generated_dir}/${target}.def")
        set(content "EXPORTS\n")
        foreach(symbol IN LISTS symbols)
            string(APPEND content "    ${symbol}\n")
        endforeach()
        file(GENERATE OUTPUT "${generated_file}" CONTENT "${content}")
        target_link_options(${target} PRIVATE "/DEF:${generated_file}" "/NOEXP")
    elseif(APPLE)
        set(generated_file "${generated_dir}/${target}.exports")
        set(content "")
        foreach(symbol IN LISTS symbols)
            string(APPEND content "_${symbol}\n")
        endforeach()
        file(GENERATE OUTPUT "${generated_file}" CONTENT "${content}")
        target_link_options(${target} PRIVATE "-Wl,-exported_symbols_list,${generated_file}")
    else()
        set(generated_file "${generated_dir}/${target}.map")
        set(content "{\n  global:\n")
        foreach(symbol IN LISTS symbols)
            string(APPEND content "    ${symbol};\n")
        endforeach()
        string(APPEND content "  local: *;\n};\n")
        file(GENERATE OUTPUT "${generated_file}" CONTENT "${content}")
        target_link_options(${target} PRIVATE
            "-Wl,--version-script=${generated_file}"
            "-Wl,--no-undefined"
        )
    endif()
endfunction()
